apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: webapp
  type: NodePort
  #loadBalancerIP: 192.168.3.29
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
